---

services:
  app:
    # DriveLedger has no published container image (yet) — build it locally.
    build: .
    image: driveledger:latest
    restart: unless-stopped
    # volumes used to keep data persistent
    volumes:
      - data:/App/data
      - keys:/root/.aspnet/DataProtection-Keys
    # expose port and/or use serving via traefik
    ports:
      - 8080:8080
    # traefik configurations, including networks can be commented out if not needed
    networks:
      - traefik-ingress
    labels:
      ## Traefik General
      # We set 'enable by default' to false, so this tells Traefik we want it to connect here
      traefik.enable: true
      # define network for traefik<>app communication
      traefik.docker.network: traefik-ingress
      ## HTTP Routers
      traefik.http.routers.driveledger.entrypoints: https
      traefik.http.routers.driveledger.rule: Host(`driveledger.mydomain.tld`)
      ## Middlewares
      #traefik.http.routers.driveledger.middlewares: authentik@docker
      # none
      ## HTTP Services
      traefik.http.services.driveledger.loadbalancer.server.port: 8080

volumes:
  data:
  keys:

networks:
  traefik-ingress:
    external: true
